### PR TITLE
Resolve shiny::bootstrapLib() before rendering

### PR DESCRIPTION
**Pull request by cpsievert**
This PR fixes the following problem with [shiny v1.6](https://github.com/rstudio/shiny/pull/3239), which will be submitted to CRAN within the next 24 hours.

```r
> disable_bootstrap_on_bookmark("test_bookmark")
Error: object of type 'closure' is not subsettable
```

Please submit this patch to CRAN as soon as possible so we can get shiny v1.6 on CRAN for `rstudio::global`.

BTW, if you're curious why this is now a problem -- `bootstrapLib()` now returns a `htmltools::tagFunction()` which doesn't get resolved until print-time, so you'll now need to resolve it by hand to achieve this dynamic disabling of bootstrap. Also, now that shiny has `session$setCurrentTheme()` it may be worth a proposal to shiny itself to make disabling a native feature (but that's for another day)

### CODE REVIEW

**Comment by marekrogala** [comment]
Thanks @cpsievert ! @dokato can't complete this now, he will merge and submit to CRAN asap but this will be tomorrow (GMT).

**Comment by cpsievert** [comment]
Good to know, thanks, please keep us updated. We're hoping to submit about 16 hours from now, so anytime before that would be super awesome!

**Review by dokato — APPROVED** [review]
LGTM, Thanks 🎉 This has been submitted to CRAN.

**Comment by cpsievert** [comment]
Awesome, thank you!

**Pull request merged**
