### PR TITLE
Server side callbacks

### PR DESCRIPTION
**Pull request by neumanrq**
Hi 👋 First of all: Thanks for your work on the `shiny.router` package!

This PR is intended as a question. For the shiny applications that I wrote at work I needed a simple routing layer that affects both, the UI elements as well as the server-side computations for the corresponding datasets. 

If I got everything correct, `shiny.router` currently manipulates only the UI layer of the shiny application. That means, the data crunching computations within the global `server` function were not touched by the routing, so currently there is no option to "redefine" them explicitly.

My questions is: Should this be possible? I'm not sure if I know enough of the overall project and situation to judge, I was just driven by my personal needs: When I constructed my applications it feels like it makes sense to define different server functions for different endpoints. So therefore I experimented with it resulting in these changes. 

Is this a direction you'd like to embrace or is this outside your planned scope of `shiny.router`? Since I'm also not 100% confident about the technical details of my approach I'd be happy to get your feedback!

### CODE REVIEW

**Comment by dokato** [comment]
Thanks @neumanrq for reaching out. We will definitely take a look on that, but the reason why it takes longer than usual is that we are currently in the process of removing js dependencies from router and using shiny hash functions instead. I will check if your changed fit into this change.

**Comment by neumanrq** [comment]
In case you are interested in my motivation for this, I made a example application with multiple endpoints, that sketches how I like to apply these kind of callbacks:

**Comment by neumanrq** [comment]
I think it could be relevant for you to know more about my motivation for this change - so I made an example app with multiple endpoints to sketch how I currently tend to use `shiny.router`, including the server callbacks: https://github.com/neumanrq/shiny.blueprint

**Comment by marekrogala** [comment]
Thanks @neumanrq ! great to see your use case; we'll try to prioritize this!

**Comment by krystian8207** [comment]
Thanks @neumanrq for implementation of your great idea with servers side callbacks.
Due to our last work on shiny.router concerned on page.js dependency removal (currently performed on dev branch) we decided to close this PR and reopened new one to `dev` branch: https://github.com/Appsilon/shiny.router/pull/42
We've adjusted your changes to our recent amendments there.
We would appreciate if you could inform us about any notes on this PR.

**Pull request closed without merging**
